In [1]:
import pandas as pd

excel_file = pd.ExcelFile(r"..\..\res\raw\Cal_Ageing_Checkup1.xlsx")
for sheet_name in excel_file.sheet_names:
    print(f"=== Sheet: {sheet_name} ===")
    df = pd.read_excel(excel_file, sheet_name=sheet_name)
    display(df)

=== Sheet: unit ===

,20240201100904-CheckUp-3-7-AM23NMC00009.xlsx,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,device,9,3,7,NaN,NaN,NaN,NaN,NaN
1,Start time,NaN,2024-02-01 10:09:04,NaN,End time,NaN,2024-02-06 12:51:31,NaN,NaN
2,NDA file path,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,List of unit plans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Time,Current,Voltage,Capacity,Energy,Power,Internal resistance,Temperature,Air pressure
5,hh:mm:ss.ms,A,V,Ah,Wh,W,mΩ,℃,kPa

=== Sheet: test ===

,Test information,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,Start step ID,NaN,1,Volt. upper,NaN,"4,3V",P/N,NaN,2024-02-01 10-09-02,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cycle count,NaN,268,Volt. lower,NaN,"2,3V",Builder,NaN,Anton Schl?sser,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Record settings,NaN,1000ms/0V/0A,Curr. upper,NaN,"12,A",Remarks,NaN,Resulution for iOCV normed to 1% for 80% SOH -...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Voltage range,NaN,5V,Curr. lower,NaN,-,-,NaN,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Current range,NaN,"+12,/-12,A(1000000,A/6000000,A/12000000,A)",Start time,NaN,2024-02-01 10:09:04,Barcode,NaN,AM23NMC00009,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Active material,NaN,-,Nominal capacity,NaN,-,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Step plan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Step Index,Step Name,Step Time(hh:mm:ss.ms),Voltage(V),C-rate(C),Current(A),Cutoff voltage (V),Cut-off C-rate(C),Cut-off curr.(A),Energy(Wh),...,Resistance(mΩ),Capacity(Ah),Record settings,Aux.CH recording condition,Max Vi(V),Min Vi(V),Max Ti(℃),Min Ti(℃),Segment record1,Segment record2
10,1,CCCV Chg,NaN,"4,2",NaN,"1,44",NaN,NaN,"0,05",NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2,Rest,00:01:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,3,CCCV DChg,NaN,"2,5",NaN,"0,96",NaN,NaN,"0,05",NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,4,Rest,00:01:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,5,CCCV Chg,NaN,"4,2",NaN,"1,44",NaN,NaN,"0,05",NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,6,Rest,00:15:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,7,CC DChg,NaN,NaN,NaN,"0,96",NaN,NaN,NaN,NaN,...,NaN,"0,0388",1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,8,Rest,00:06:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,9,Cycle,Start step ID:7,Cycle count:155,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,10,CCCV DChg,NaN,"2,5",NaN,"0,96",NaN,NaN,"0,05",NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,11,Rest,00:15:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,12,CC Chg,NaN,NaN,NaN,"1,44",NaN,NaN,NaN,NaN,...,NaN,"0,0388",1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,13,Rest,00:06:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,14,Cycle,Start step ID:12,Cycle count:155,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,15,CCCV Chg,NaN,"4,2",NaN,"1,44",NaN,NaN,"0,05",NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,16,Rest,01:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1000ms/0V/0A,NaN,NaN,NaN,NaN,NaN,NaN,NaN

=== Sheet: cycle ===

,Cycle Index,Chg. Cap.(Ah),DChg. Cap.(Ah),Chg.-DChg. Eff(%),Chg. Energy(Wh),DChg. Energy(Wh),Chg. Time,DChg. Time
0,1,8.6984,4.8156,180.63,33.5840,17.8031,06:59:05.600,05:07:54.400
1,2,0.0000,0.0388,0.00,0.0000,0.1600,00:00:00.000,00:02:25.500
2,3,0.0000,0.0388,0.00,0.0000,0.1594,00:00:00.000,00:02:25.500
3,4,0.0000,0.0388,0.00,0.0000,0.1590,00:00:00.000,00:02:25.500
4,5,0.0000,0.0388,0.00,0.0000,0.1586,00:00:00.000,00:02:25.500
...,...,...,...,...,...,...,...,...
263,264,0.4480,0.0600,746.73,1.7665,0.2190,00:16:40.100,00:00:30.000
264,265,0.4480,0.0600,746.70,1.7963,0.2236,00:16:40.100,00:00:30.000
265,266,0.4466,0.0600,744.32,1.8272,0.2274,00:16:40.100,00:00:30.000
266,267,0.4324,0.0600,720.60,1.7937,0.2323,00:16:40.200,00:00:30.000
267,268,3.5424,5.6460,62.74,13.1759,20.2963,03:46:47.100,02:03:43.400

=== Sheet: step ===

,Cycle Index,Step Index,Step Number,Step Type,Step Time,Oneset Date,End Date,Capacity(Ah),Energy(Wh),Oneset Volt.(V),End Voltage(V)
0,1,1,1,CCCV Chg,03:12:01.900,2024-02-01 10:09:04,2024-02-01 13:21:06,3.9174,15.3228,3.5269,4.2003
1,1,2,2,Rest,00:01:00.000,2024-02-01 13:21:06,2024-02-01 13:22:06,0.0000,0.0000,4.1990,4.1978
2,1,3,3,CCCV DChg,05:05:28.900,2024-02-01 13:22:06,2024-02-01 18:27:34,4.7768,17.6422,4.1754,2.5001
3,1,4,4,Rest,00:01:00.000,2024-02-01 18:27:34,2024-02-01 18:28:34,0.0000,0.0000,2.5018,2.5184
4,1,5,5,CCCV Chg,03:47:03.700,2024-02-01 18:28:34,2024-02-01 22:15:38,4.7811,18.2612,2.5634,4.2003
...,...,...,...,...,...,...,...,...,...,...,...
489,241,12,490,CC Chg,00:01:37.100,2024-02-03 07:00:31,2024-02-03 07:02:08,0.0388,0.1625,4.1628,4.1980
490,241,13,491,Rest,00:06:00.000,2024-02-03 07:02:08,2024-02-03 07:08:08,0.0000,0.0000,4.1646,4.1383
491,242,12,492,CC Chg,00:01:00.500,2024-02-03 07:08:08,2024-02-03 07:09:09,0.0242,0.1014,4.1716,4.2001
492,242,15,493,CCCV Chg,00:27:44.800,2024-02-03 07:09:09,2024-02-03 07:36:54,0.1342,0.5636,4.1996,4.2003
493,242,16,494,Rest,01:00:00.000,2024-02-03 07:36:54,2024-02-03 08:36:54,0.0000,0.0000,4.1991,4.1890

=== Sheet: record ===

,DataPoint,Step Type,Time,Total Time,Current(A),Voltage(V),Capacity(Ah),Energy(Wh),Date,Power(W)
0,1,CCCV Chg,00:00:00.000,00:00:00.000,1.4378,3.5269,0.0000,0.0000,2024-02-01 10:09:04,5.0709
1,2,CCCV Chg,00:00:01.000,00:00:01.000,1.4398,3.5287,0.0004,0.0014,2024-02-01 10:09:05,5.0804
2,3,CCCV Chg,00:00:02.000,00:00:02.000,1.4400,3.5298,0.0008,0.0028,2024-02-01 10:09:06,5.0828
3,4,CCCV Chg,00:00:03.000,00:00:03.000,1.4400,3.5307,0.0012,0.0042,2024-02-01 10:09:07,5.0842
4,5,CCCV Chg,00:00:04.000,00:00:04.000,1.4401,3.5315,0.0016,0.0056,2024-02-01 10:09:08,5.0856
...,...,...,...,...,...,...,...,...,...,...
167858,167859,Rest,00:59:56.000,46:26:37.700,0.0000,4.1889,0.0000,0.0000,2024-02-03 08:36:50,0.0000
167859,167860,Rest,00:59:57.000,46:26:38.700,0.0000,4.1890,0.0000,0.0000,2024-02-03 08:36:51,0.0000
167860,167861,Rest,00:59:58.000,46:26:39.700,0.0000,4.1890,0.0000,0.0000,2024-02-03 08:36:52,0.0000
167861,167862,Rest,00:59:59.000,46:26:40.700,0.0000,4.1889,0.0000,0.0000,2024-02-03 08:36:53,0.0000
167862,167863,Rest,01:00:00.000,46:26:41.700,0.0000,4.1890,0.0000,0.0000,2024-02-03 08:36:54,0.0000

=== Sheet: log ===

   No.  DataPoint                 Time   Class                   Event
0    1          1  2024-02-01 10:09:04  Prompt                   Start
1    2          1  2024-02-01 10:09:04  Prompt  Channel status changed
2    3    1679280  2024-02-06 12:51:31  Prompt                  Finish
3    4    1679280  2024-02-06 12:51:31  Prompt  Channel status changed

=== Sheet: idle ===

Empty DataFrame
Columns: [No., DataPoint, Date, State, Voltage(V), Current(A), V1(V), T1(℃)]
Index: []

=== Sheet: auxVol ===

       Unnamed: 0           Unnamed: 1 Single cell voltage(V) Unnamed: 3
0       DataPoint                 Date                     V1    Aux. ΔV
1               1  2024-02-01 10:09:04                      0          0
2               2  2024-02-01 10:09:05                      0          0
3               3  2024-02-01 10:09:06                      0          0
4               4  2024-02-01 10:09:07                      0          0
...           ...                  ...                    ...        ...
167859     167859  2024-02-03 08:36:50                      0          0
167860     167860  2024-02-03 08:36:51                      0          0
167861     167861  2024-02-03 08:36:52                      0          0
167862     167862  2024-02-03 08:36:53                      0          0
167863     167863  2024-02-03 08:36:54                      0          0

[167864 rows x 4 columns]

=== Sheet: auxTemp ===

       Unnamed: 0           Unnamed: 1 Single cell temperature(℃) Unnamed: 3
0       DataPoint                 Date                         T1    Aux. ΔT
1               1  2024-02-01 10:09:04                       27.8          0
2               2  2024-02-01 10:09:05                       27.8          0
3               3  2024-02-01 10:09:06                       27.8          0
4               4  2024-02-01 10:09:07                       27.8          0
...           ...                  ...                        ...        ...
167859     167859  2024-02-03 08:36:50                       25.3          0
167860     167860  2024-02-03 08:36:51                       25.3          0
167861     167861  2024-02-03 08:36:52                       25.3          0
167862     167862  2024-02-03 08:36:53                       25.3          0
167863     167863  2024-02-03 08:36:54                       25.1          0

[167864 rows x 4 columns]